gcp_project = "entur-1287"
gcp_storage_project = "entur-ror-prod"
gcp_pubsub_project = "entur-ror-prod"
gcp_resources_project = "entur-ror-prod"
kube_namespace = "production"
bucket_marduk_instance_name = "marduk-production"
bucket_nisaba_instance_name = "ror-nisaba-production"
bucket_nisaba_exchange_instance_name = "ror-nisaba-exchange-production"
service_account_bucket_role = "roles/storage.admin"

