/*
 * Licensed under the EUPL, Version 1.2 or – as soon they will be approved by
 * the European Commission - subsequent versions of the EUPL (the "Licence");
 * You may not use this work except in compliance with the Licence.
 * You may obtain a copy of the Licence at:
 *
 *   https://joinup.ec.europa.eu/software/page/eupl
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the Licence is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the Licence for the specific language governing permissions and
 * limitations under the Licence.
 *
 */

package no.entur.nisaba.config;

import jakarta.annotation.PostConstruct;
import no.entur.nisaba.avro.NetexImportEvent;
import org.apache.avro.util.ClassSecurityValidator;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.context.annotation.Configuration;

/**
 * Declares the Avro records generated from {@code src/main/avro} as trusted Avro classes.
 * <p>
 * Since Avro 1.12.2, {@link ClassSecurityValidator} guards every class that Avro resolves by name
 * and trusts only a handful of JDK types by default. The Kafka consumer route is configured with
 * {@code specificAvroReader=true}, so the Confluent {@code KafkaAvroDeserializer} resolves the
 * reader class from the writer schema name. Without this configuration every poll fails with
 * {@code SecurityException: Forbidden no.entur.nisaba.avro.NetexImportEvent!}, the import date map
 * is never populated and the timetable-import-info API returns 404.
 * <p>
 * The global validator is always composed from {@link ClassSecurityValidator#DEFAULT} rather than
 * from the current global instance. This keeps the Avro defaults (the JDK types and the
 * {@code org.apache.avro.SERIALIZABLE_CLASSES} / {@code org.apache.avro.SERIALIZABLE_PACKAGES}
 * system properties, which remain available as an operational override), and it makes the
 * registration idempotent: repeated application context refreshes cannot build up an ever deeper
 * chain of nested validators.
 */
@Configuration
public class AvroClassSecurityConfig {

    private static final Logger LOGGER = LoggerFactory.getLogger(AvroClassSecurityConfig.class);

    /**
     * The Avro records generated by the avro-maven-plugin from {@code src/main/avro}.
     * A new schema added there must be declared here as well.
     */
    private static final ClassSecurityValidator.ClassSecurityPredicate NISABA_AVRO_CLASSES =
            ClassSecurityValidator.builder()
                    .add(NetexImportEvent.class)
                    .build();

    /**
     * Installs the Avro class security validator on the startup thread.
     * Camel is started as a {@code SmartLifecycle} once the application context refresh is
     * complete, that is after every singleton has been initialized, so this runs before the Kafka
     * consumer route starts and therefore before the first record is deserialized.
     */
    @PostConstruct
    void trustNisabaAvroClasses() {
        ClassSecurityValidator.setGlobal(
                ClassSecurityValidator.composite(ClassSecurityValidator.DEFAULT, NISABA_AVRO_CLASSES)
        );
        LOGGER.info("Registered {} as a trusted Avro class", NetexImportEvent.class.getName());
    }
}
